# Generated by Django 4.2.29 on 2026-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_visibility_notification_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_background',
            field=models.ImageField(blank=True, null=True, upload_to='chat_bg/'),
        ),
    ]
